import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          {" "}
          <nav className="bg-gray-800 p-4">
            <div className="flex space-x-6">
              <Link
                href="/"
                className="text-white hover:text-gray-300 transition-colors"
              >
                Home
              </Link>
              <Link
                href="/blog"
                className="text-white hover:text-gray-300 transition-colors"
              >
                Blog
              </Link>
              <Link
                href="/products"
                className="text-white hover:text-gray-300 transition-colors"
              >
                Products
              </Link>
              <Link
                href="/contact"
                className="text-white hover:text-gray-300 transition-colors"
              >
                Contact
              </Link>
              <Link
                href="/login"
                className="text-white hover:text-gray-300 transition-colors"
              >
                Login
              </Link>
            </div>
          </nav>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
