import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow-sm border-b">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">
              <div className="flex items-center">
                <h1 className="text-xl font-semibold text-gray-900">My App</h1>
              </div>
              <nav className="flex space-x-8">
                <Link href="/" className="text-gray-500 hover:text-gray-900">
                  Home
                </Link>
                <Link href="/task-csr" className="text-gray-500 hover:text-gray-900">
                  task-csr
                </Link>
                <Link href="/task-isr" className="text-gray-500 hover:text-gray-900">
                  task-isr
                </Link>
                <Link href="/task-ssg" className="text-gray-500 hover:text-gray-900">
                  task-ssg
                </Link>
                <Link href="/task-ssr" className="text-gray-500 hover:text-gray-900">
                  task-ssr
                </Link>
              </nav>
            </div>
          </div>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
